version: '3'

services:
    ecommerce-admin-image:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: ecommerce-admin-container
        ports:
            - '3005:3005'
